server:
  port: 8080

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    status-page-url-path: /info
    health-check-url-path: /health

zuul:
  sensitiveHeaders:
  ignored-services: '*'
  routes:
    authorization-service:
      path: /auth/**
      #stripPrefix: false
      url: http://localhost:9208/
    user-service:
      path: /user-api/**
    inventory-service:
      path: /inventory-api/**

ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true

security:
  oauth2:
    client:
      client-id: webshop-webclient
      client-secret: supersecretpassword
      access-token-uri: http://docker.for.win.localhost:9208/oauth/token
      grant-type: authorization_code
      user-authorization-uri: http://docker.for.win.localhost:9208/oauth/authorize
      scope: all.read all.write
    resource:
      filter-order: 3
      jwk:
        key-set-uri: http://docker.for.win.localhost:9208/oauth2/jwks.json



